### PR TITLE
use desktop launch interface

### LINKED ISSUE #209: Add open button to AppPage installed page tiles
The open button won't work in the snap yet.  We have a branch of snapd that adds app launch from another snap capability, but that will take a while to land, it's huge.  Can you hide the open button if $SNAP is set in the environment?

_Originally posted by @kenvandine in https://github.com/ubuntu-flutter-community/software/issues/205#issuecomment-1247477123_

### PR DESCRIPTION
**Pull request by d-loose**
Uses [snapcraft_launcher.dart](https://github.com/d-loose/snapcraft_launcher.dart) to launch desktop applications from other snaps.
Fix #209

### CODE REVIEW

**Comment by d-loose** [comment]
To test this locally:
- build the snap, install it, connect all plugs except for `desktop-launch` - there should be no 'open' buttons on the collection page
- connect the `desktop-launch` interface, relaunch the app - there should be 'open' buttons for all snaps that provide a desktop entry on the collection page

**Comment by d-loose** [comment]
Yes

**Comment by Feichtmeier** [comment]
Runs quite far then fails with 
```bash
2023-03-08 10:01:04.645 :: 2023-03-08 09:01:02.684 :: [   +3 ms] "flutter linux" took 4,830ms.
2023-03-08 10:01:04.645 :: 2023-03-08 09:01:02.692 :: [   +5 ms] Error: No pubspec.yaml file found.
2023-03-08 10:01:04.645 :: 2023-03-08 09:01:02.692 ::            This command should be run from the root of your Flutter project.
2023-03-08 10:01:04.645 :: 2023-03-08 09:01:02.692 :: [   +2 ms]
2023-03-08 10:01:04.645 :: 2023-03-08 09:01:02.692 ::            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
```
I use snapcraft from edge, version is snapcraft 7.3.post11+git1fee3d83   

[snapcraft-20230308-095608.999984.log](https://github.com/ubuntu-flutter-community/software/files/10919001/snapcraft-20230308-095608.999984.log)

**Comment by d-loose** [comment]
I doubt that this is a problem with this particular PR though, since it only adds the `desktop-launch` plug to the snapcraft.yaml. Can you successfully build a snap from the main branch?

**Comment by Feichtmeier** [comment]
> I doubt that this is a problem with this particular PR though, since it only adds the `desktop-launch` plug to the snapcraft.yaml. Can you successfully build a snap from the main branch?

woops, nope, same error -.-

As I am struggling to get any snap build (currently trying the music snap also), would be better if Ken reviews this

**Comment by Feichtmeier** [comment]
Okay! I am back on track with lessons learned from music snap :D  
reason for those funny errors was that I was running snapcraft from snap dir. kinda weird error outputs though

anyways! could build the snap but when I run it

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.1191" (uid=1000 pid=306605 comm="/snap/snap-store/x1/bin/software " label="snap.snap-store.snap-store (enforce)") interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" error name="(unset)" requested_reply="0" destination="org.freedesktop.NetworkManager" (uid=0 pid=1535 comm="/usr/sbin/NetworkManager --no-daemon " label="unconfined")
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1124)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2      DBusRemoteObjectManager.getManagedObjects (package:dbus/src/dbus_remote_object_manager.dart:80)
<asynchronous suspension>
#3      NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2351)
<asynchronous suspension>
#4      ConnectivityLinux._startListenConnectivity (package:connectivity_plus_linux/src/connectivity.dart:61)
<asynchronous suspension>
```

and no snap-store process is running
(I removed the snap before installing yours dangerous)

**Comment by d-loose** [comment]
You need to manually connect the respective plugs, e.g. `snap connect snap-store:network-manager`

**Review by Feichtmeier — APPROVED** [review]
Works :clap: :+1: 

grafik

disconnected from desktop launch:
grafik

**Pull request merged**
