### PR TITLE
ODRS ratings

### PR DESCRIPTION
**Pull request by jpnurmi**
NOTE: Only _ratings_ - not reviews. :)

| Explore | Snap | Deb |
|---|---|---|
| Screenshot from 2023-01-31 21-38-54 | Screenshot from 2023-01-31 21-39-14 | Screenshot from 2023-01-31 21-39-19 |

Ref: #872

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Amazomg @jpnurmi ! 💪 

Did you check the start-up / search performance with this new service?

**Comment by jpnurmi** [comment]
The ODRS server can be sometimes a bit slow and unstable, and the API is not ideal because it only allows downloading them all as a bundle. Therefore, ratings are cached into `~/.cache/software/odrs/ratings.json` and thanks to the earlier changes they are now entirely decoupled from the app data to avoid blocking the GUI.

You can test it by inserting an artificial delay like this:
```diff
diff --git a/lib/services/odrs_service.dart b/lib/services/odrs_service.dart
index eeed16f..2fd9861 100644
--- a/lib/services/odrs_service.dart
+++ b/lib/services/odrs_service.dart
@@ -38,6 +38,7 @@ class OdrsService {
     }
     if (!exists || await file.expired(_kCachePeriod)) {
       try {
+        await Future.delayed(const Duration(seconds: 5));
         final ratings = await _client.getRatings();
         yield ratings;
         await file.writeRatings(ratings);
```
On the first startup, the ratings appear after the delay but on the second startup, they're read from the cache.

[Screencast from 2023-01-31 22-13-39.webm](https://user-images.githubusercontent.com/140617/215885214-1037dd21-18fc-4b68-a777-50b3235959cf.webm)

**Review by Feichtmeier — APPROVED** [review]
OKay nice, since they are decoupled and do not steal frames from anywhere I am fine with the first start delay 👍 
Thanks again! 💪

**Comment by jpnurmi** [comment]
There's caching on two levels. First of all, we need a cache file to be able to restore the last known ratings as quickly as possible. The cache file has an expiry time of 1 hour. If the timestamp is older than that when asking for ratings, it returns the last known ratings immediately anyway and then re-fetches new ones. Secondly, we don't want to access the cache file repeatedly so the model keeps its own cache with a bit shorter expiry time.

**Pull request merged**
