### PR TITLE
Remove extra bottom padding from MyApps page.

### PR DESCRIPTION
**Pull request by whiskeyPeak**
Slipped through #679 :sweat_smile: 

Before:
Screenshot from 2023-01-04 20-17-16

After:
Screenshot from 2023-01-04 20-17-49

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@whiskeyPeak thanks for this

Could you resolve the conflicts so we can get this in?

**Comment by Feichtmeier** [comment]
Uhm... When did you remove the adaptive padding?

**Comment by whiskeyPeak** [comment]
> Uhm... When did you remove the adaptive padding?

You removed it here: https://github.com/ubuntu-flutter-community/software/pull/696/files :eyes:

**Comment by Feichtmeier** [comment]
But only for the medium window

**Comment by Feichtmeier** [comment]
I'll double check the padding everywhere tomorrow

**Comment by whiskeyPeak** [comment]
> But only for the medium window

Yeah, the small and medium layouts both use the OnePageLayout widgets, and because the padding is now always constant for both pages the adaptivePadding and windowSize variables are not used anymore, even though they're passed down in the constructor.

**Pull request merged**
