### PR TITLE
UpdatePage: change from Grid to ListView with adaptive padding

### PR DESCRIPTION
**Pull request by Feichtmeier**
https://user-images.githubusercontent.com/15329494/183880537-5796f5d7-3fce-4a47-957c-9e3484b3f84c.mp4

@madsrh this changes only the gridview to a listview plus some padding depending on screenwidth. Other changes can be done in a different PR - is this okay for you like this? 

Ref #81

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Bonus: when you click one of the banners
grafik

a dialogue with more info appears, though I did not yet figure out why the license is not displayed
grafik

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/183921855-25218b4a-6c99-4243-8582-45cb0f006ac1.mp4

**Comment by madsrh** [comment]
I have not tested this yet but it looks brilliant 🎉

**Comment by Feichtmeier** [comment]
grafik

@madsrh ?

**Comment by Feichtmeier** [comment]
the changelog info is currently not receiveable via packagekit.dart I think. I asked robert maybe he has an idea

**Pull request merged**
