### PR TITLE
Issue 1186 review

### LINKED ISSUE #1178: reviews: change write a review button label
The button to write a review is currently displayed as 'Your review'. The current label is quite vague, doesn't tell the user what will happen when pressed. It's good usability practice to use action verbs, to explain what will happen next

We should change the label to 'Write a review'.

Screenshot 2023-03-22 at 16 02 37

wireframes
Screenshot 2023-03-22 at 16 08 14

### LINKED ISSUE #1182: star ratings: change text label
This might be nitpicking, but currently, the text label reads 'Click to rate:'. 
I got the feedback that it is quite redundant telling the users to click. 

Having 'Rate:' should be sufficient.

Screenshot 2023-03-23 at 11 28 58

### LINKED ISSUE #1183: star ratings: improve
Not sure about the real size of the (clickable) stars, but they look small for something that is interactive.
For better accessibility, we should make them bigger, ideally the same height as the button.

Screenshot 2023-03-23 at 11 52 35

### PR DESCRIPTION
**Pull request by madsrh**
This is as far as I can go. I have no idea how to add a link or create a hover animation 🤷‍♂️ 

But this fixes some of the issues in 1186 

Fixes #1182
Fixes #1183
Fixes #1178

image

image

### CODE REVIEW

**Comment by madsrh** [comment]
I'm back! 😎

**Comment by Feichtmeier** [comment]
hehe, thanks mads :)

just remove the unused import
    info • Unused import: 'package:url_launcher/url_launcher.dart' • lib/app/common/app_page/app_reviews.dart:14:8 • unused_import

**Review by Feichtmeier — APPROVED** [review]

**Comment by Feichtmeier** [comment]
Could you link the correct issues in the pr description and change the pr name please

**Comment by Feichtmeier** [comment]
See the issues burning away like tiner :fire: :laughing:

**Pull request merged**
