### PR TITLE
Add verification status to account

### LINKED ISSUE #162: Add verification status to account
There is no way to verify if the software from that account is verified.

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

CC @madsrh @mivoligo 

Things got crowded in there. So to fix this issue and clean up the header, I exchanged the semantics for the external link button with the homepage link. Combined with the verified icon if the publisher is verified.

Toolip
grafik

I moved the contact and website links (as they are two separate things sometimes, sometimes the same) to the description expandable:

grafik

Sorry for the german :P 

Any idea where to move the "open app" button now and how it should look?

Fixes #162

Ref #91

### CODE REVIEW

**Comment by Feichtmeier** [comment]
How about clicking the app icon opens the app? :)

grafik

**Comment by Feichtmeier** [comment]
Damn Paul, this is the solution! :+1: :D 

grafik

I like it

**Comment by Jupi007** [comment]
Looks very good :D

**Comment by madsrh** [comment]
What Paul said 😅

Looks great 🎉

**Comment by mivoligo** [comment]
Really nice :)
Not sure how it's now with the scrolling. It would be great if those buttons were always visible.

**Comment by Feichtmeier** [comment]
> 

The buttons at the bottom are always visible
The part that is scrollable is the middle (called it "content")

**Comment by kenvandine** [comment]
The open button won't work in the snap yet.  We have a branch of snapd that adds app launch from another snap capability, but that will take a while to land, it's huge.  Can you hide the open button if $SNAP is set in the environment?

**Comment by Feichtmeier** [comment]
Should be possible to bring this top down from main, yes

**Pull request merged**
