### PR TITLE
Settings: move to trailing & open in dialog

### PR DESCRIPTION
**Pull request by Feichtmeier**
I think it would be better to open the settings page without the need to leave the current page.

Any veto @anasereijo @madsrh @Jupi007 @d-loose  or @jpnurmi ? :smile_cat: 

Edit: if we merge this I will change the other dialogs on this page to be inside the settings dialog instead of opening a new one

grafik
grafik

### CODE REVIEW

**Comment by Jupi007** [comment]
Imo, it is a good idea 👍

**Comment by madsrh** [comment]
Much better! That page always felt a bit disconnected from the others 👍

**Comment by Feichtmeier** [comment]
Cool! 4 Thumbs up :sob: :star: 

Navigating to repo settings and about (minus licenses) is now in a navigator:

grafik

Sources: ->

grafik

About: ->

grafik

I think this is enough for one PR

**Comment by Feichtmeier** [comment]
woops, one tiny thing, background color for the darktheme :P 

grafik

**Review by madsrh — APPROVED** [review]

**Comment by whiskeyPeak** [comment]
Wow, this looks so much better!

**Pull request merged**
