### PR TITLE
Changes searchfield font size

### PR DESCRIPTION
**Pull request by madsrh**
Okay, please check this code - It took me all day and I must have visited every site on Google looking for a way to fix this 😅

I also made the clear icon a bit stronger. WDYT?

Ikke-navngivet-2

### Before
image

image

### After
image

image

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
Great, it looks much better!

**Comment by Feichtmeier** [comment]
The font looks better but I think the text field height changes

**Comment by madsrh** [comment]
> but I think the text field height changes

This is smaller, yes. Do you prefer the current height even with the smaller text @Feichtmeier ?

**Comment by Feichtmeier** [comment]
i am not sure, I found it always very hard to find the correct size here. If we find a solution I would love some generic headerbar textfield sizes for all our apps : D
Would it be possible to have the font change without the size change?

**Comment by madsrh** [comment]
> Would it be possible to have the font change without the size change?

Yes, I changed it deliberate. Like this?

image

**Comment by Feichtmeier** [comment]
yeah maybe you are right. I think the textfield should be as tall as buttons, 40 pixels, just curious how does a button look alongside of this textfield?

**Comment by madsrh** [comment]
image

**Comment by Feichtmeier** [comment]
Let's give it a try and see if this sticks

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
