### PR TITLE
SearchField on the AppPage

### LINKED ISSUE #855: Searchbar on the apppage
As a result of the meeting:

- make the search available on the AppPage

@d-loose could you eventually tackle this one?

### PR DESCRIPTION
**Pull request by Feichtmeier**
https://user-images.githubusercontent.com/15329494/219010891-9713e0e6-3143-4b53-a4f2-1fc3cd6ac6bf.mp4

Fixes #855

### CODE REVIEW

**Comment by Feichtmeier** [comment]
search field blinks... needs more work

**Comment by Feichtmeier** [comment]
mehh, can't make this jumping go away. any idea @d-loose ?

**Comment by d-loose** [comment]
You can try what I did in the [previous PR](https://github.com/ubuntu-flutter-community/software/pull/914/files#diff-8a501980c8ad61f8a9da60054bd888a93dad5147e812f847704b3af08a89dfbe).

But aren't we running into the problem again that it's not clear what the search bar should do on an `AppPage` reached from the collection page?

**Comment by Feichtmeier** [comment]
> You can try what I did in the [previous PR](https://github.com/ubuntu-flutter-community/software/pull/914/files#diff-8a501980c8ad61f8a9da60054bd888a93dad5147e812f847704b3af08a89dfbe).
> 
> But aren't we running into the problem again that it's not clear what the search bar should do on an `AppPage` reached from the collection page?

I changed the search to happen only on enter on the AppPage. This should be a safe approach IMO

**Comment by Feichtmeier** [comment]
> You can try what I did in the [previous PR](https://github.com/ubuntu-flutter-community/software/pull/914/files#diff-8a501980c8ad61f8a9da60054bd888a93dad5147e812f847704b3af08a89dfbe).
> 
> But aren't we running into the problem again that it's not clear what the search bar should do on an `AppPage` reached from the collection page?

oh... collectionpage... :thinking:

**Comment by Feichtmeier** [comment]
yeah you are right. I think there we need a sidebar trick again. Damn it. I close this

**Pull request closed without merging**
