### PR TITLE
Improved colors for Games banner

### PR DESCRIPTION
**Pull request by madsrh**
image

### CODE REVIEW

**Comment by madsrh** [comment]
lol, I commited the other example @Jupi007 😅  

TBH I'm still unsure if this is better than [the current](https://user-images.githubusercontent.com/3986894/220791206-3fd2c825-c592-42cc-bc84-96d904d5f888.png)

**Comment by Jupi007** [comment]
Yeah, I even think this is worst than the current look 😅

**Comment by madsrh** [comment]
I think you're right 🤷‍♂️ this is SO hard, because there's so many options. I'll close this one.

**Comment by Jupi007** [comment]
Working on gradients is always very hard, indeed. Three quarters of the time it looks ugly 😅

**Pull request closed without merging**
