### PR TITLE
ExplorePage: add animated icon if disconnected

### LINKED ISSUE #73: ExplorePage: add animated icon if disconnected
Similar to the firefox / thunderbird images shown on errors  / empty search / success

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2022-09-18 23-09-57

I need to fix this problem with transparent color.

Fixes #73

### CODE REVIEW

**Comment by Jupi007** [comment]
@Feichtmeier What do you think of temporary use a non transparent color awaiting I fix https://github.com/ubuntu/yaru_icons.dart/issues/62 ?

**Comment by Feichtmeier** [comment]
Ofc! which color is transparent?

**Comment by Jupi007** [comment]
The one used to draw the icon use transparency :D
So let's do this 👍 I'll try grey50

**Comment by Jupi007** [comment]
Capture d’écran du 2022-09-21 22-00-56

@Feichtmeier ?

**Comment by Feichtmeier** [comment]
Looks good!

**Pull request merged**
