### PR TITLE
Cancel a background updates check when opening the details page for a package.

### LINKED ISSUE #465: Cancel a background updates check when opening the details page for a package
This is related to #444.

Because packagekit.dart serializes requests, we cannot run concurrently an updates check and retrieve the details for a given package.
When a user searches for packages and opens the details page for a given package, we should cancel any ongoing updates check to retrieve the details for the package as fast as possible.

### PR DESCRIPTION
**Pull request by oSoMoN**
Fixes #465.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
hmmmmm doesn't seem to work for me

https://user-images.githubusercontent.com/15329494/199493281-3427a09a-6695-4a80-9b11-9a17306a4e23.mp4
(sorry for the music)

**Comment by oSoMoN** [comment]
That's because this change will cancel the currently running updates check only when opening the details page for a given package. I overlooked that it should be cancelled when opening the search/my apps pages as well. I'll work on this.

**Comment by d-loose** [comment]
Has this become obsolete thanks to #567?

**Comment by Feichtmeier** [comment]
@d-loose for package pages loaded with appstream infos yes. But not for example for a case where we check for updates and then someone clicks on a deb in the filemanager. THe app does nto break but if there are really many updates the AppLoading page is probably shown for a long time

**Comment by d-loose** [comment]
@Feichtmeier but this PR resolves exactly that - it cancels an ongoing update in `PackageModel.init`

https://user-images.githubusercontent.com/113362648/211818847-736a2d4b-4a71-4102-8d64-d25a439e4a6f.mp4

**Comment by Feichtmeier** [comment]
> @Feichtmeier but this PR resolves exactly that - it cancels an ongoing update in `PackageModel.init`
> 2023-01-11.14-30-26.mp4

then we need this PR I think :), or ?

**Comment by d-loose** [comment]
Ah yes, of course - I thought I asked whether it needs additional work.. Since the issue you described earlier got fixed by #567 I think it's good to go as it is.

**Comment by Feichtmeier** [comment]
There are bunch of conflicts though

grafik

**Comment by Feichtmeier** [comment]
Merged in the other PR, thank you @oSoMoN !

**Pull request closed without merging**
