### PR TITLE
 let the deb icons fade in/out to indicate that the mapping is loading

### LINKED ISSUE #1254: let the deb icons fade in/out to indicate that the mapping is loading
Wouldn't this mapping be cached? So it would only be slow on the first launch or if there's new apps on the Explore page?

I know you didn't ask, but I'm personally not a fan of the accentcolored cof logo 😅 

Another idea would be to let the deb icons fade in/out to indicate that the mapping is loading 🤷‍♂️ 

https://github.com/ubuntu-flutter-community/software/assets/3986894/efb5de52-c694-448b-bd33-2c4e821d59d7

_Originally posted by @madsrh in https://github.com/ubuntu-flutter-community/software/discussions/1236#discussioncomment-5942617_

### PR DESCRIPTION
**Pull request by Feichtmeier**
[Bildschirmaufzeichnung vom 2023-06-04, 12-24-43.webm](https://github.com/ubuntu-flutter-community/software/assets/15329494/3b63a7a6-b21f-40bf-8886-74c2029dee4e)

Fixes #1254

### CODE REVIEW

**Review by madsrh — APPROVED** [review]
I love this! 🥳

**Comment by Feichtmeier** [comment]
Oh 😮
I shouldn't have use auto merge when I want all people to approve

@anasereijo @d-loose if you have any veto I can revert

**Comment by madsrh** [comment]
I mean something that indicates that the Debs are loading. Let's try this for now, but really, the icons could be fading, scaling, changing color or even rotating 😅 So I'm keen to know if anyone has a better idea @Jupi007 @anasereijo

**Comment by Jupi007** [comment]
Honestly, more I look at, more I think it looks like the deb icon got a brilliant sheen 😅
In my opinion, this doesn't really mean "wait, we check if this app is available as deb".

What about hide the deb/snap icon while loading the mapping (we can show a spinning loader with the same soft grey used by icons during this period), and then fade in the available package format icons when the mapping is loaded.
This way would be more obvious for me.

**Pull request merged**
