### PR TITLE
Update banners, navigation and colors to new yaru widgets

### PR DESCRIPTION
**Pull request by Feichtmeier**
~~@jpnurmi managed to get everything back like it was except there is a weird thing, when switching themes, the banners remain in the old color~~

### CODE REVIEW

**Comment by jpnurmi** [comment]
Is the issue related to yaru_widgets? I can reproduce the same even with the current Software main:

```diff
diff --git a/lib/store_app/explore/section_grid.dart b/lib/store_app/explore/section_grid.dart
index b3372bf..f0c0767 100644
--- a/lib/store_app/explore/section_grid.dart
+++ b/lib/store_app/explore/section_grid.dart
@@ -61,7 +61,8 @@ class SectionGrid extends StatelessWidget {
         final snap = sections.take(initialAmount).elementAt(index);
 
         final banner = YaruBanner(
-          title: Text(snap.name),
+          // title: Text(snap.name),
+          title: Text(Theme.of(context).brightness.name),
           subtitle: Text(
             snap.summary,
             overflow: TextOverflow.ellipsis,
```

image

**Comment by Feichtmeier** [comment]
No idea really. Hm but I managed to fix it

**Comment by jpnurmi** [comment]
Printf-debugging reveals that it's not using the correct brightness, though:

```diff
diff --git a/lib/store_app/explore/section_grid.dart b/lib/store_app/explore/section_grid.dart
index f95ae67..31d15ab 100644
--- a/lib/store_app/explore/section_grid.dart
+++ b/lib/store_app/explore/section_grid.dart
@@ -60,6 +60,8 @@ class SectionGrid extends StatelessWidget {
       itemBuilder: (context, index) {
         final snap = sections.take(initialAmount).elementAt(index);
 
+        print(Theme.of(context).brightness);
+
         final banner = YaruBanner.tile(
           surfaceTintColor: Theme.of(context).brightness == Brightness.light
               ? kBannerBgLight
```

**Comment by Feichtmeier** [comment]
I'll fix the theme of calls

**Comment by jpnurmi** [comment]
Moving the inherited Theme dependency up from the grid builder to the grid helps:
```diff
diff --git a/lib/store_app/explore/section_grid.dart b/lib/store_app/explore/section_grid.dart
index f95ae67..19a6806 100644
--- a/lib/store_app/explore/section_grid.dart
+++ b/lib/store_app/explore/section_grid.dart
@@ -50,6 +50,8 @@ class SectionGrid extends StatelessWidget {
     final sections = model.sectionNameToSnapsMap[snapSection] ?? [];
     if (sections.isEmpty) return const SizedBox();
 
+    final brightness = Theme.of(context).brightness;
+
     return GridView.builder(
       physics: ignoreScrolling ? const NeverScrollableScrollPhysics() : null,
       padding:
@@ -60,11 +62,12 @@ class SectionGrid extends StatelessWidget {
       itemBuilder: (context, index) {
         final snap = sections.take(initialAmount).elementAt(index);
 
+        print(brightness);
+
         final banner = YaruBanner.tile(
-          surfaceTintColor: Theme.of(context).brightness == Brightness.light
-              ? kBannerBgLight
-              : kBannerBgDark,
-          elevation: Theme.of(context).brightness == Brightness.light
+          surfaceTintColor:
+              brightness == Brightness.light ? kBannerBgLight : kBannerBgDark,
+          elevation: brightness == Brightness.light
               ? kBannerElevationLight
               : kBannerElevationDark,
           title: Text(snap.name),
```

**Comment by Feichtmeier** [comment]
I'll fix the theme of calls me

**Comment by Feichtmeier** [comment]
> Moving the inherited Theme dependency up from the grid builder to the grid helps:
> 
> ```diff
> diff --git a/lib/store_app/explore/section_grid.dart b/lib/store_app/explore/section_grid.dart
> index f95ae67..19a6806 100644
> --- a/lib/store_app/explore/section_grid.dart
> +++ b/lib/store_app/explore/section_grid.dart
> @@ -50,6 +50,8 @@ class SectionGrid extends StatelessWidget {
>      final sections = model.sectionNameToSnapsMap[snapSection] ?? [];
>      if (sections.isEmpty) return const SizedBox();
>  
> +    final brightness = Theme.of(context).brightness;
> +
>      return GridView.builder(
>        physics: ignoreScrolling ? const NeverScrollableScrollPhysics() : null,
>        padding:
> @@ -60,11 +62,12 @@ class SectionGrid extends StatelessWidget {
>        itemBuilder: (context, index) {
>          final snap = sections.take(initialAmount).elementAt(index);
>  
> +        print(brightness);
> +
>          final banner = YaruBanner.tile(
> -          surfaceTintColor: Theme.of(context).brightness == Brightness.light
> -              ? kBannerBgLight
> -              : kBannerBgDark,
> -          elevation: Theme.of(context).brightness == Brightness.light
> +          surfaceTintColor:
> +              brightness == Brightness.light ? kBannerBgLight : kBannerBgDark,
> +          elevation: brightness == Brightness.light
>                ? kBannerElevationLight
>                : kBannerElevationDark,
>            title: Text(snap.name),
> ```

yep figured it out :D
Will do this in the whole app soon. Sometimes when I am in a rush I mess up with  the .of calls too much

**Pull request merged**
