### PR TITLE
Fix: Can't switch snap tracking channel without reinstalling

### LINKED ISSUE #1069: Can't switch snap tracking channel without reinstalling
[Screencast from 2023-02-16 11-47-13.webm](https://user-images.githubusercontent.com/113362648/219344084-4d5e003f-b400-46a9-be8d-ff5ea10f5150.webm)

### PR DESCRIPTION
**Pull request by Feichtmeier**
https://user-images.githubusercontent.com/15329494/219354485-be88a826-3b71-46b3-a7cd-15f8855d1ef8.mp4

Fixes #1069

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I guess this is also a great candidate for the integration test ;)

**Review by d-loose — APPROVED** [review]
Thanks, LGTM :+1:

**Comment by d-loose** [comment]
> I guess this is also a great candidate for the integration test ;)

Yes! More tests!

**Comment by d-loose** [comment]
On second thought, we should compare channels, not versions. Users might want to track a different channel even if this doesn't change the currently installed version (e.g. 'candidate/stable' and 'candidate/edge' might point to the same version at some point, but a user might want to switch from stable to edge in order to receive updates more quickly)

**Pull request merged**
