### PR TITLE
Remove unnecessary toolips

### PR DESCRIPTION
**Pull request by madsrh**
@Feichtmeier @local-optimum @Jupi007 continuing to explore a solution to  [#887](https://github.com/ubuntu-flutter-community/software/issues/887) on how to avoid redundant information, could this solution work?

- removed unnecessary tooltips
- added a length threshold for Version and Publisher

### CODE REVIEW

**Comment by Feichtmeier** [comment]
No we need these tooltips for when the information can't be read because the string is too long

**Comment by madsrh** [comment]
> No we need these tooltips for when the information can't be read because the string is too long

I didn't remove all of them 🤔 you can always read the remaining strings. Eg. Date will never be longer than xx/xx/xxxx. I tried with the smallest possible window side.

**Comment by Feichtmeier** [comment]
License can be super long

**Comment by madsrh** [comment]
> License can be super long

Good point. There's even support for custom licenses.

This was the longest string I could find for testing 😁 

image

**Comment by Feichtmeier** [comment]
grafik

works

**Comment by madsrh** [comment]
> works

image

😮 I must have opened 100 different apps, looking for a license with a long name and you just happened to know this one?

**Review by Feichtmeier — APPROVED** [review]

**Comment by Feichtmeier** [comment]
I knew this one :P  From testing this app through months I have some funny things to use for testing
Like intellij apps with channels

**Pull request merged**
