### PR TITLE
Set align to center for titles in the sidebar

### LINKED ISSUE #181: Set align to center for titles in the sidebar
Set align to center for titles in the sidebar. Otherwise, the text looks weird.

Снимок экрана от 2022-09-07 16-49-06

### PR DESCRIPTION
**Pull request by DefaultX-od**
While I was translating software app to Russian, I found out how bizarre, sidebar looks like:

Снимок экрана от 2022-09-07 16-48-37

It looks WAY too big, if you ask me... And I've decided to add new line symbol between words: "Мои" and "Приложения". Here is the result:

Снимок экрана от 2022-09-07 16-49-06

As you can see, text looks strange like that, and I've decided to set text align to center, for every title in the sidebar, even through only one title was affected, because I thought, what if some other language will have way too big title translation to fit in one line, but for different category? And here is the result:

Снимок экрана от 2022-09-07 16-49-41

Looks way more polished. What do you guys think?

Fixes #181

### CODE REVIEW

**Comment by Jupi007** [comment]
Hi @DefaultX-od,
thanks for your PR, it is much appreciated!

But you need to create a linked issue where we can discuss of the problem before working on a PR :)
You also need to sign the Canonical CLA. If you agree, you have to use the exactly same email address used to push your changes to Github.

I'm currently working on a new version of this navigation rail in yaru_widgets (related issue: https://github.com/ubuntu/yaru_widgets.dart/
I agree it looks better with a center aligned text.
But imo, it is something which need to be fixed with a generic widget, which define itself `text-align: center` to its children with a `TextTheme`.
Like this, we would avoid code repetition.

**Comment by Feichtmeier** [comment]
Thanks @DefaultX-od for the idea
Let's to this in yaru widgets as @Jupi007 suggested.

The navigationrail also has more problems, which is why @Jupi007 is working on a replacement
Could you use this PR-header to create a new issue? your pictures describe very precisely the problem of the current navigation for long text. :)

Thank you for wanting to add russian translations - please do this in another PR if you have time
(And as jupi said don't forget to link an issue to your PR and also sign the CLA with the exact email your commits are made here.) Thanks in advance

**Comment by DefaultX-od** [comment]
изображение

Is this how I should fill in this field?

**Comment by DefaultX-od** [comment]
I've signed CLA just now

**Comment by DefaultX-od** [comment]
> Hi @DefaultX-od, thanks for your PR, it is much appreciated!
> 
> But you need to create a linked issue where we can discuss of the problem before working on a PR :) You also need to sign the Canonical CLA. If you agree, you have to use the exactly same email address used to push your changes to Github.
> 
> I'm currently working on a new version of this navigation rail in yaru_widgets (related issue: [ubuntu/yaru_widgets.dart#175](https://github.com/ubuntu/yaru_widgets.dart/issues/175)) I agree it looks better with a center aligned text. But imo, it is something which need to be fixed with a generic widget, which define itself `text-align: center` to its children with a `TextTheme`. Like this, we would avoid code repetition.

Sure, a general solution to a problem is better.

**Comment by Jupi007** [comment]
> Sure, a general solution to a problem is better.

Thanks @DefaultX-od :)

**Comment by DefaultX-od** [comment]
> Thanks @DefaultX-od for the idea Let's to this in yaru widgets as @Jupi007 suggested. (here is the issue [ubuntu/yaru_widgets.dart#175](https://github.com/ubuntu/yaru_widgets.dart/issues/175))
> 
> The navigationrail also has more problems, which is why @Jupi007 is working on a replacement Could you use this PR-header to create a new issue? your pictures describe very precisely the problem of the current navigation for long text. :)
> 
> Thank you for wanting to add russian translations - please do this in another PR if you have time (And as jupi said don't forget to link an issue to your PR and also sign the CLA with the exact email your commits are made here.) Thanks in advance

I'm still working on the translation, testing the app with it to find out how do I feel about it. But sure, when I'm done with it, I'll make sure to create an issue first, and then a separate PR for my translation.

**Comment by Feichtmeier** [comment]
@DefaultX-od since we agreed on fixing this in yaru_widgets - would you mind closing this PR?

**Comment by DefaultX-od** [comment]
> @DefaultX-od since we agreed on fixing this in yaru_widgets - would you mind closing this PR?

Sure.

**Pull request closed without merging**
