### PR TITLE
Add Portuguese translation

### PR DESCRIPTION
**Pull request by hugok79**
Add Portuguese translation (Portugal)

### CODE REVIEW

**Comment by hugok79** [comment]
I already signed... is probably not synced yet. I am a long-time ubuntu translator.

**Comment by Feichtmeier** [comment]
Hi @hugok79 thank you very much!

Yeah this CI is a bit slow ...
I'll test tomorrow again and the day after 😺
Thanks!

**Comment by Feichtmeier** [comment]
Just if you did not know: please use the very same e-mail you signed the CLA with in this commit here

**Comment by Feichtmeier** [comment]
This commit here https://github.com/ubuntu-flutter-community/software/commit/27a5483572c345fadec0af55a60e4e221cbcf4a8.patch was made by Hugo Carvalho <hugokarvalho@hotmail.com>

Did you enter this email in the CLA? =)

**Comment by hugok79** [comment]
> This commit here https://github.com/ubuntu-flutter-community/software/commit/27a5483572c345fadec0af55a60e4e221cbcf4a8.patch was made by Hugo Carvalho [hugokarvalho@hotmail.com](mailto:hugokarvalho@hotmail.com)
> 
> Did you enter this email in the CLA? =)

@Feichtmeier Yes.

**Comment by Feichtmeier** [comment]
Now it worked
Thank you for your patience 😺

**Pull request merged**
