### PR TITLE
Small styling fixes for dependecies popup

### PR DESCRIPTION
**Pull request by madsrh**
Very small improvements towards #739

- moved expander to start
- removed text changing (feels weird that the text changes when expanded)
- added border

As you can see there's still some issues. Just a placeholder until some advanced help (not me) arrives implementing [this idea 🖼️  ](https://github.com/ubuntu-flutter-community/software/issues/739#issuecomment-1399258699)

### CODE REVIEW

**Comment by Feichtmeier** [comment]
But this text was included in the mock up by @anasereijo 
Double check with her please

**Comment by anasereijo** [comment]
heyy this is looking good, @madsrh 👍 

I think it's okay to leave the dropdown text as 'Dependencies' as long as it stays the same when expanded.

I have one suggestion: is it possible to make the list of dependencies a bit more compact (as per my mock-up)? It will help to reduce the amount of scrolling.

Thanks!

**Review by Feichtmeier — APPROVED** [review]
lgtm

**Comment by anasereijo** [comment]
> I was thinking the same about the orange text (not just because it's orange), but it also changes when expanded. IMO just plain text would be fine. WDYT @Feichtmeier @anasereijo ? Should I add this to the PR?

I agree 💯

**Comment by madsrh** [comment]
> I agree 💯

> lgtm

Now I'm confused 😀 @Feichtmeier was so fast. Do you want this in a new PR or did you merge because the current "lgtm"?

**Pull request merged**
