### PR TITLE
fix(packagekit): ensure packagekit daemon is active

### LINKED ISSUE #1215: unable to see debs tabs of installed apps
image

### PR DESCRIPTION
**Pull request by d-loose**
Temporary workaround for PackageKit-related AppArmor denials.

Fix #1215

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Awesome that you found a fix! If this works do you think that this could also be moved (some time) to packagekit.dart instead?

**Comment by d-loose** [comment]
> If this works do you think that this could also be moved (some time) to packagekit.dart instead?

No, this has nothing to do with PackageKit's DBus API and has no place in `packagekit.dart`.
I hope the underlying issue is fixed elsewhere, though - as far as I understand calling a well-known DBus method should start the service, see https://dbus.freedesktop.org/doc/system-activation.txt

**Comment by d-loose** [comment]
> Can the packagkit invocation done within the snap confinement? I mean, as you described [here](https://github.com/ubuntu-flutter-community/software/issues/1215#issuecomment-1558878140), I am really curious about that

Yes, that's allowed by the `desktop-legacy` interface. This workaround seems a bit hacky, so we should definitely understand and resolve the underlying issue.

I'd be happy if someone could build a snap and check that everything works:
* run `snapcraft` in this PR branch (make sure the working directory is clean)
* install the snap with `snap install --dangerous ..`
* connect all slots:
```sh
for slot in snap-store:appstream-metadata snap-store:packagekit-control snap-store:snapd-control snap-store:network-manager-observe snap-store:network-manager snap-store:desktop-launch; do sudo snap connect $slot; done
```
* check that the application runs without any AppArmor denials when the packagekit service is inactive
```sh
systemctl stop packagekit.service
snap-store
```

**Comment by soumyaDghosh** [comment]
## Works just as expected
[Screencast from 2023-05-24 20-49-53.webm](https://github.com/ubuntu-flutter-community/software/assets/72045785/54bf4c73-676d-4301-a14e-4716593327b8)

**Comment by d-loose** [comment]
Thanks a lot for testing!
I'd be happy to merge this for now and come back to it once we have a better solution.
I've opened a [topic in the snapcraft forums](https://forum.snapcraft.io/t/apparmor-denial-in-new-snap-store-despite-connected-packagekit-control-interface/35290).

**Review by Feichtmeier — APPROVED** [review]
Thank you!

**Comment by soumyaDghosh** [comment]
Trigger the build please!!!! Soon :-)

**Comment by Feichtmeier** [comment]
it is automatically triggered every X hours, I think at least 2 times a day

**Comment by soumyaDghosh** [comment]
How is it done? the auto trigger?

**Pull request merged**
