### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Ubuntu Software Store/ubuntu-software](https://hosted.weblate.org/projects/ubuntu-software/ubuntu-software/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by jpnurmi** [comment]
I think somebody needs to press the reset button in Weblate... It keeps submitting the same commits again and again.

**Comment by jpnurmi** [comment]
I've never run into this kind of loop with Weblate but here's what I'd try to get out of it:
1) lock the Weblate project
2) push any pending changes from Weblate
3) merge this if there's any diff
4) reset and unlock Weblate

**Comment by seb128** [comment]
The actual changeset was empty there even after force pushing the current translations from weblate so I did a force reset on the weblate side now, you can close this merge request and let's see if that resolved the issue...

**Comment by jpnurmi** [comment]
Great, thanks @seb128!

**Pull request closed without merging**
