### PR TITLE
New banner gradients

### PR DESCRIPTION
**Pull request by madsrh**
Fixes https://github.com/ubuntu-flutter-community/software/issues/1011

Discussed here: https://github.com/ubuntu-flutter-community/software/discussions/1014#discussioncomment-5077295

This was harder than it looks! What we had was already pretty good for some categories. I felt a bit constraint by the limited selection, but tried my best to match the colors to a category. WDYT? @Zoospora @Feichtmeier @Jupi007

image
image
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Feichtmeier** [comment]
There are some nice improvements over the current! IMO it's good

**Comment by madsrh** [comment]
> There are some nice improvements over the current! IMO it's good

It is mostly **Games** that I'm unhappy with, but let's give it a try for a while.

**Comment by anasereijo** [comment]
This is looking great @madsrh 👍 

> It is mostly Games that I'm unhappy with, but let's give it a try for a while.

Feel free to propose a new gradient!

**Comment by Zoospora** [comment]
Good work! They really look cool. 🤩 There is no problem in adding more gradients, we just need to take accessibility into account, but I don't think it's a closed thing. In fact it's something we can work on little by little.

**Review by Feichtmeier — APPROVED** [review]
Since ana² approved I approve too so github let's us merge this =)

**Comment by Feichtmeier** [comment]
Ah did you remove the "hello mads... gradiensts...." comment? :)

**Comment by madsrh** [comment]
> Ah did you remove the "hello mads... gradiensts...." comment? :)

Incoming PR 🤣

**Pull request merged**
