### PR TITLE
Use shimmer effect for loading content

### LINKED ISSUE #344: Use shimmer effect for loading content
For all pages (Explore, MyApps, AppPage) it would be nice to have a shimmer effect for loading content, instead of spinning indicators.
We could use this package for this

https://pub.dev/packages/shimmer

### PR DESCRIPTION
**Pull request by Feichtmeier**
https://user-images.githubusercontent.com/15329494/202524552-0809325d-4ffa-4d65-89d4-3d904edd20b0.mp4

https://user-images.githubusercontent.com/15329494/202526447-7668194e-cc3d-4c2d-845e-5ddf04c70aa7.mp4

Ref #344

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@madsrh @anasereijo 
Any improvement ideas?

**Comment by Jupi007** [comment]
I think you miss a placeholder for each secondary part like the image, the (sub)title, buttons, infos, ...
But maybe wait for the page design to be stabilized before create those placeholder.

**Comment by Feichtmeier** [comment]
I think this would look too busy. But I can try

**Comment by Jupi007** [comment]
> I think this would look too busy.

I don't think so because it is the mean of this shimmer effect :)
You can see something similar when load youtube with a "slow" internet connection: video title, description, buttons, they are all placeholders.

**Comment by madsrh** [comment]
> Any improvement ideas?

Nope, from your video this looks perfect 👌 As @Jupi007 says, this can be tweaked when the layout is final. Your internet is too fast - good thing you can slow down the video on GitHub.

**Comment by Feichtmeier** [comment]
Hmmm, testing a little:


https://user-images.githubusercontent.com/15329494/202549315-83dfdc09-189b-4232-ae44-fd1c4f3660ff.mp4

IMHO this looks too busy, especially if you think this normally is only there for 1-2 secs max
Or do you mean more like 1 shimmer for each fake container? @Jupi007

**Comment by Jupi007** [comment]
Yes I mean a shimmer for each container 🙂

**Comment by madsrh** [comment]
This _does_ look pretty cool 😎  
Skærmbillede 2022-11-17 kl  21 23 58

**Comment by Feichtmeier** [comment]
I am really not sure. Especially in the normal window size there is so much happening there
I change the PR description to Ref instead of Closes and then we can try to improve it

**Pull request merged**
