### PR TITLE
Add Japanese Translation

### LINKED ISSUE #177: Add Japanese Translation

### PR DESCRIPTION
**Pull request by oyajun**
Fixes #177

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@oyajun thanks for this!

You need to sign the contributor agreement in order to let the first test pass :)
https://ubuntu.com/legal/contributors/agreement
If you agree make sure to take the exact mail address this commit is made with

**Comment by oyajun** [comment]
@Feichtmeier
What should I enter this form?
image

**Comment by Feichtmeier** [comment]
I think Ken VanDine should be okay :) (he is the ubuntu desktop leader)

**Comment by oyajun** [comment]
I have signed contributor agreement.

**Comment by Feichtmeier** [comment]
Maybe this cla thing needs some time before it recognises your email. I'll re run it in some hours

**Comment by Feichtmeier** [comment]
I think you've got two email adresses, right?
https://github.com/ubuntu-flutter-community/software/commit/f0d087c3b38113ddab461598d648fe3de0118059.patch
uses oyamadajun@outlook.jp
but the test fails with
Checking the following users on Launchpad:
- guyluz11@gmail.com ✕ (has not signed the CLA)

I am sorry, this is not very nice for new contributors :( I hope we can make this process more easy in the future

**Comment by Feichtmeier** [comment]
@oSoMoN do you know how often the CLA fetches information from launchpad for a new CLA-signer and his email?
We got three PRs with all of them failing due to the CLA check. :(

**Comment by oSoMoN** [comment]
I can see that [~oyajun](https://launchpad.net/~oyajun) is a member of [~contributor-agreement-canonical](https://launchpad.net/~contributor-agreement-canonical), and it says here "joined 4 hours ago", after the last re-run of the check. @Feichtmeier can you try running it again?

(I just ran the script locally and it passes here, so it should be fine now)

**Pull request merged**
