### PR TITLE
Tweak responsive layout for app page

### LINKED ISSUE #312: Tweak responsive layout for app page
On the "frontpage" the main container has a fixed position. On the app page the main container is moving right, down and is stretched as you resize the window.

Could we, like the frontpage, use a fixed position and after a certain width (in my example below it's 1220px) then center the content?

image

It's a bad description of the issue, so I've made a very quick mockup 😁 Does this make sense @Feichtmeier ? I'll tag @anasereijo for comments

https://user-images.githubusercontent.com/3986894/193156542-dfd3f27a-c0e4-428d-b3c7-6a017b600e44.mp4

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #312

### CODE REVIEW

**Comment by madsrh** [comment]
I don't have time to test this until this weekend, but feel free to merge it if you agree 😃

**Comment by Feichtmeier** [comment]
@madsrh 

[Bildschirmaufzeichnung vom 30.09.2022, 10:06:14.webm](https://user-images.githubusercontent.com/15329494/193222895-468e9865-3a50-4581-90a0-5ade37329232.webm)

**Comment by Feichtmeier** [comment]
ok maybe this is better @madsrh 

[Bildschirmaufzeichnung vom 30.09.2022, 10:49:22.webm](https://user-images.githubusercontent.com/15329494/193231803-73bf9978-9f13-4e07-a7f7-b1b3614d8696.webm)

**Comment by Jupi007** [comment]
Hmm, maybe something intermediary between your two screencast?
I have the feeling that the first one is too large, and the second one is too small.

**Comment by madsrh** [comment]
It has to have a fixed margin (to the sidebar) until the width reaches max

**Comment by Feichtmeier** [comment]
A fixed margin is not so good because you see a jump eventually and it doesn't scale
I now use the might of math lol 😂

I can tweak the function later and repost the result

**Comment by Feichtmeier** [comment]
@madsrh @Jupi007 

[Bildschirmaufzeichnung vom 30.09.2022, 12:12:55.webm](https://user-images.githubusercontent.com/15329494/193248348-5e39c677-3f8d-4023-b952-a68c581ebcf8.webm)

?

**Comment by Feichtmeier** [comment]
[tadah.webm](https://user-images.githubusercontent.com/15329494/193249472-d40b1a44-36e2-4df9-a846-de3617cc587c.webm)

@madsrh @Jupi007 ?

**Comment by Jupi007** [comment]
Honestly, on a 1920 screen I think the right content bar is a bit too small.
Both columns are currently 1/2, but I think the left one should be 2/5, and the right one 3/5.

**Comment by Feichtmeier** [comment]
grafik

?

**Comment by Jupi007** [comment]
Much better :+1:

**Comment by Feichtmeier** [comment]
ok merging then, we can tweak it more later if needed

**Pull request merged**
