### PR TITLE
UpdatePage: improve update count visualization

### LINKED ISSUE #238: Updating one package returns "everything is up to date"
When you only install one package the text implies that there are no more updates. It should just say something like "Update installed / install finished / done! / ..."

image

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #238

### CODE REVIEW

**Comment by madsrh** [comment]
Yes, thanks! This works @Feichtmeier 

We would problery want some kind of notification that X-name package has been updated. Could we use [desktop_notifications](https://pub.dev/packages/desktop_notifications) or do you think it would be better to do it inside the app (like Nautilus does)?

**Comment by Feichtmeier** [comment]
Yes we're already using desktop notifications for installation events

Something like 
X have been updated
But wait! There is more! Is not really need for  within the app
I think we can trust users to see that the list of updates shrinked

**Comment by Feichtmeier** [comment]
Let's do this in another issue/pr ok @madsrh ?

**Comment by madsrh** [comment]
> Let's do this in another issue/pr ok madsrh ?

OFC, I'm afk for work. Can you?

**Review by madsrh — APPROVED** [review]

**Pull request merged**
