### PR TITLE
ci: Add dependabot

### LINKED ISSUE #1246: Add dependabot for dependency management
Dependabot could be added to the CI workflow to handle dependency management.

### PR DESCRIPTION
**Pull request by dejvizelo**
Adds dependabot for dependency version updates on a weekly basis

Close #1246

### CODE REVIEW

**Comment by dejvizelo** [comment]
Who can I reference as a `Canonical Project Manager` in the [CLA form](https://ubuntu.com/legal/contributors/agreement)?

**Comment by Feichtmeier** [comment]
hi @dejvizelo thanks for taking the time to contribute to this projects!
You were so fast that I didn't find time to reply to your issue : D because I think we have already a solution for this inside this orga. 
@jpnurmi is the renovate bot a solution to this issue linked in this PR?

**Comment by jpnurmi** [comment]
There's not much difference between dependabot and renovate, either works just fine. It's a matter of taste but in my opinion, renovate's interactive dashboard is nicer for managing updates.

If you want to go with renovate, you can configure and enable it for specific repositories in the organization settings:
https://github.com/organizations/ubuntu-flutter-community/settings/installations

Click configure renovate, scroll down, select repos, and click save.

**Comment by jpnurmi** [comment]
I just enabled renovate for [odrs.dart](https://github.com/ubuntu-flutter-community/odrs.dart). This is how the process looks:

After selecting the repo in the organization settings, renovate automatically created a PR to configure itself:
- https://github.com/ubuntu-flutter-community/odrs.dart/pull/9

After merging the PR, renovate created a dashboard where you can see updates, trigger re-runs etc.
- https://github.com/ubuntu-flutter-community/odrs.dart/issues/11

And it proposed a PR to update glib:
- https://github.com/ubuntu-flutter-community/odrs.dart/pull/10

**Comment by jpnurmi** [comment]
> Who can I reference as a `Canonical Project Manager` in the [CLA form](https://ubuntu.com/legal/contributors/agreement)?

You can add Ken VanDine (ken.vandine {at} canonical {dot} com)

Not sure how one is supposed to find this but I just happen to know the page exists :)

https://canonical.com/projects/directory

**Comment by dejvizelo** [comment]
> You can add Ken VanDine (ken.vandine {at} canonical {dot} com)

Thank you! I guess this issue can be closed.

**Pull request closed without merging**
