### PR TITLE
Translation to Spanish.

### PR DESCRIPTION
**Pull request by Cubel89**
Has been created the file Spanish language and all the texts present have been translated.

### CODE REVIEW

**Comment by Cubel89** [comment]
I've already signed... It's the first time I start collaborating on a project like this and I don't know how to solve the problem.

**Comment by Feichtmeier** [comment]
Hi @Cubel89 
Thank you very much for your contribution :)!

Don't panic, this CI is slow as hell :older_adult: 

I'll check from time to time and re-run the CI

**Comment by Feichtmeier** [comment]
Just if you did not know: please use the very same e-mail you signed the CLA with in this commit here

**Comment by Feichtmeier** [comment]
The commit here (https://github.com/ubuntu-flutter-community/software/commit/6bbff72a9c825ed08a0fabbf08215a5df9ff0e3c.patch) was made by

user.name: Cubel 
user.email: p.cubel@gmail.com

Did you enter this email in the CLA?

**Comment by Cubel89** [comment]
Sorry, I had not seen the message.
Yes, it is the email that I put. p.cubel@gmail.com. If you want, I can fill out the form again.

I had doubts when filling in the section "Please add the Canonical Project Manager or contact". Is it possible that the information in this section is wrong?

**Comment by Cubel89** [comment]
Just a few minutes ago I received an email from Canonical Contributor Agreement

**Comment by Feichtmeier** [comment]
Thank you! :) Now it worked
We need to improve this CLA process, thanks for your patience

**Comment by Feichtmeier** [comment]
I'll add you to the contributors list

**Pull request merged**
