### PR TITLE
Replacing some dependencies from git to their pub.dev version

### LINKED ISSUE #146: Using snapd version from pub.dev
https://github.com/ubuntu-flutter-community/software/blob/b96857ae0e09e29553fc5e72c4301b75c5215b80/pubspec.yaml#L36

I think it will be better to use the packages versions from pub.dev instead of directly from the GitHub repo
https://pub.dev/packages/snapd

This can help a number of ways, the first one that come to my mind is more organized version control.
New versions will need to be updated manually inside pubspec.yaml but the app version can be directly connected to specific package version for issues and to know if a new feature has arrived.

### PR DESCRIPTION
**Pull request by guyluz11**
Closes #146

### CODE REVIEW

**Comment by guyluz11** [comment]
`yaru_icons` and `yaru_widgets` do not have last version in pub.dev and it causes some error when trying to use pub.dev version.

`yaru_widgets` error:

``` dart
ERROR: lib/store_app/updates/updates_page.dart:364:17: Error: The method 'YaruAnimatedOkIcon' isn't defined for the class '_NoUpdatesPage'.
ERROR:  - '_NoUpdatesPage' is from 'package:software/store_app/updates/updates_page.dart' ('lib/store_app/updates/updates_page.dart').
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'YaruAnimatedOkIcon'.
ERROR:                 YaruAnimatedOkIcon(
ERROR:                 ^^^^^^^^^^^^^^^^^^
ERROR: lib/store_app/updates/update_banner.dart:45:11: Error: No named parameter with the name 'bannerWidth'.
ERROR:           bannerWidth: 500,
ERROR:           ^^^^^^^^^^^
ERROR: ../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/yaru_widgets-1.1.1/lib/src/yaru_banner.dart:6:9: Context: Found this candidate, but the arguments don't match.
ERROR:   const YaruBanner({
ERROR:         ^^^^^^^^^^
Exception: Build process failed
```

So I didn't changed them

**Comment by Jupi007** [comment]
@guyluz11 I just published **yaru_widgets.dart** `v1.1.2` and **yaru_icons.dart** `v0.2.2`. So you can use them in this PR :)

**Comment by guyluz11** [comment]
> `yaru_icons` and `yaru_widgets` do not have last version in pub.dev and it causes some error when trying to use pub.dev version.
> 
> `yaru_widgets` error:
> 
> ```dart
> ERROR: lib/store_app/updates/updates_page.dart:364:17: Error: The method 'YaruAnimatedOkIcon' isn't defined for the class '_NoUpdatesPage'.
> ERROR:  - '_NoUpdatesPage' is from 'package:software/store_app/updates/updates_page.dart' ('lib/store_app/updates/updates_page.dart').
> ERROR: Try correcting the name to the name of an existing method, or defining a method named 'YaruAnimatedOkIcon'.
> ERROR:                 YaruAnimatedOkIcon(
> ERROR:                 ^^^^^^^^^^^^^^^^^^
> ERROR: lib/store_app/updates/update_banner.dart:45:11: Error: No named parameter with the name 'bannerWidth'.
> ERROR:           bannerWidth: 500,
> ERROR:           ^^^^^^^^^^^
> ERROR: ../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/yaru_widgets-1.1.1/lib/src/yaru_banner.dart:6:9: Context: Found this candidate, but the arguments don't match.
> ERROR:   const YaruBanner({
> ERROR:         ^^^^^^^^^^
> Exception: Build process failed
> ```
> 
> So I didn't changed them

@Jupi007 after pulling from master I still getting the error with packages version `yaru_icons: ^0.2.2`  `yaru_widgets: ^1.1.1`

**Comment by Jupi007** [comment]
Indeed, please use `yaru_widgets: ^1.1.2`.
I'm really sorry, I was sure I had uploaded it yesterday 🤕

**Comment by Feichtmeier** [comment]
You need to sign the contributor agreement in order to let the first test pass :)
https://ubuntu.com/legal/contributors/agreement
If you agree make sure to take the exact mail address this commit is made with

**Comment by guyluz11** [comment]
Done

> You need to sign the contributor agreement in order to let the first test pass :) https://ubuntu.com/legal/contributors/agreement If you agree make sure to take the exact mail address this commit is made with

Done

**Pull request merged**
