### PR TITLE
UpdatesPage: improve tab styling

### PR DESCRIPTION
**Pull request by Feichtmeier**
Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by Feichtmeier** [comment]
I should change the text to match the title text font size

**Comment by madsrh** [comment]
This is better. Is that the standard padding? Personally and nitpicking, I would add a bit more. It looks fine in your screenshot, but in English the end of "Debian Packages" is a bit cramped.

image

**Review by madsrh — APPROVED** [review]

**Comment by whiskeyPeak** [comment]
I feel like it would look a tad better if it were centered taking the window control buttons width into consideration. Kinda like it used to look before.

**Comment by madsrh** [comment]
> I feel like it would look a tad better if it were centered taking the window control buttons width into consideration. 

+1 and the sidebar 😉 
I think this is because this PR is for the button styling only and the centering-stuff is dependent on another issue being fixed.

**Comment by Feichtmeier** [comment]
Morning :tea: :sun_behind_large_cloud: 

Yes the spacing was odd, I think it is centred now plus I fixed the tab style to look like titles:
grafik

**Comment by Feichtmeier** [comment]
Wow I think I need to learn more about auto-merge :smile: 

1) requested review
2) enabled auto-merge
3) disabled auto-merge because we found issues
4) you approved the PR but left comments
5) I change things
6) re-requested review
7) enable auto-merge and because "it was once approved" it got auto-merged without your second approval :shrug:

**Pull request merged**
