### PR TITLE
SnapDialog: add tooltips for the timestamps fields.

### PR DESCRIPTION
**Pull request by oSoMoN**

### CODE REVIEW

**Comment by oSoMoN** [comment]
image

**Comment by Feichtmeier** [comment]
Thanks! Good idea

Just one thing - could you move the abstraction of null & DateTime --> string back to the model? 😺

**Comment by Feichtmeier** [comment]
In the end this might all be opinion, but the more logic you add in the view the less readable the whole tree becomes, from my experience. :)

**Comment by Jupi007** [comment]
You could add a private method to free up the widget tree.

**Comment by Feichtmeier** [comment]
You are right, since locals are connected to the build context it shouldn't be localised in the model

**Comment by Feichtmeier** [comment]
grafik

I think it's not working as expected :) I'll dig in

**Pull request merged**
