### PR TITLE
PackageInstaller: use localisation

### LINKED ISSUE #143: PackageInstaller: use localisation

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

Fixes #143

### CODE REVIEW

**Comment by Jupi007** [comment]
Ofc, I'll test that :)

**Comment by Feichtmeier** [comment]
Woops I missed to actually use them :D

grafik

Works :) Sorry for the noise without double checking

**Review by Jupi007 — APPROVED** [review]
Works for me too :)

image

Just can you add this translation for "packageInstaller": `Installateur de paquets`

**Comment by Feichtmeier** [comment]
okay :P  
What about
"requireRestartSystem": "Restart system to finalize updates",
  "requireRestartSession": "Logout to finalize updates",
  "requireRestartApp": "Restart the app to finalize updates",

**Comment by Jupi007** [comment]
Wait, merge this PR as it.
I'll do another one with missing FR translations 🙂

**Pull request merged**
