### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [ubuntu-software/ubuntu-software](https://hosted.weblate.org/projects/ubuntu-software/ubuntu-software/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by oSoMoN** [comment]
@bittin, @fthx, @sukso96100: the CLA check claims that you haven't signed the [Canonical CLA](https://ubuntu.com/legal/contributors), which is required for contributions to this project. Would you mind doing that? Thanks!

**Comment by sukso96100** [comment]
> @bittin, @fthx, @sukso96100: the CLA check claims that you haven't signed the [Canonical CLA](https://ubuntu.com/legal/contributors), which is required for contributions to this project. Would you mind doing that? Thanks!

I remember i already signed with help from @jpnurmi does it still says i didn't signed yet?

**Comment by bittin** [comment]
@oSoMoN did so now

**Comment by oSoMoN** [comment]
Nevermind me, it turns out the CLA isn't really required for translations, only for code contributions.
We'll be looking at ignoring the CLA check on pull requests originating from Weblate.

**Review by oSoMoN — APPROVED** [review]

**Comment by bittin** [comment]
Ah alright i see, well i signed it anyways

**Pull request merged**
