### PR TITLE
Translated using Weblate (Spanish)

### PR DESCRIPTION
**Pull request by seb128**
Currently translated at 100.0% (150 of 150 strings)

Translation: Ubuntu Software Store/ubuntu-software
Translate-URL: https://hosted.weblate.org/projects/ubuntu-software/ubuntu-software/es/

### CODE REVIEW

**Comment by seb128** [comment]
The change in #720 wasn't enough to fix weblate because the project is configured with a rebase workflow, that one should do the trick and resolve the conflict

**Comment by seb128** [comment]
Could someone review that one, it should be trivial and would allow to unblock translations which are currently locked

**Review by Feichtmeier — APPROVED** [review]
looking good :smile: 

Thank you @seb128 for taking the time!

**Comment by seb128** [comment]
Thanks @Feichtmeier!

**Pull request merged**
