### PR TITLE
Add Finnish translation (create  app_fi.arb)

### PR DESCRIPTION
**Pull request by LINUX-SAUNA**
Add a Finnish language translation.

### CODE REVIEW

**Comment by LINUX-SAUNA** [comment]
> Hey! LINUX-SAUNA has not signed the Canonical CLA which is required to get this contribution merged on this project.
> 
> Please head over to https://ubuntu.com/legal/contributors to read more about it.

Did now sign it.

**Comment by Feichtmeier** [comment]
Thank you very much! :)

Eventually this needs 1 or two days until your email adress in launchpad is synced and this CI sees it, I will re-run it tomorrow

**Comment by Feichtmeier** [comment]
This commit here was made by
https://github.com/ubuntu-flutter-community/software/commit/f8ad43b8fc3cf0dc87706ae4a9064b8773ac45da.patch
user.name: LINUX-SAUNA
user.email: 113482201+LINUX-SAUNA@users.noreply.github.com

Did you enter this e-mail in the CLA?

**Comment by LINUX-SAUNA** [comment]
> This commit here was made by https://github.com/ubuntu-flutter-community/software/commit/f8ad43b8fc3cf0dc87706ae4a9064b8773ac45da.patch user.name: LINUX-SAUNA user.email: [113482201+LINUX-SAUNA@users.noreply.github.com](mailto:113482201+LINUX-SAUNA@users.noreply.github.com)
> 
> Did you enter this e-mail in the CLA?

No i most definitely did not use such (113482201+LINUX-SAUNA@users.noreply.github.com). I have no idea where that even came from!

**Comment by LINUX-SAUNA** [comment]
> > This commit here was made by https://github.com/ubuntu-flutter-community/software/commit/f8ad43b8fc3cf0dc87706ae4a9064b8773ac45da.patch user.name: LINUX-SAUNA user.email: [113482201+LINUX-SAUNA@users.noreply.github.com](mailto:113482201+LINUX-SAUNA@users.noreply.github.com)
> > Did you enter this e-mail in the CLA?
> 
> No i most definitely did not use such ([113482201+LINUX-SAUNA@users.noreply.github.com](mailto:113482201+LINUX-SAUNA@users.noreply.github.com)). I have no idea where that even came from!

I guess we'll have to do that CLA again?

**Comment by LINUX-SAUNA** [comment]
> > This commit here was made by https://github.com/ubuntu-flutter-community/software/commit/f8ad43b8fc3cf0dc87706ae4a9064b8773ac45da.patch user.name: LINUX-SAUNA user.email: [113482201+LINUX-SAUNA@users.noreply.github.com](mailto:113482201+LINUX-SAUNA@users.noreply.github.com)
> > Did you enter this e-mail in the CLA?
> 
> No i most definitely did not use such ([113482201+LINUX-SAUNA@users.noreply.github.com](mailto:113482201+LINUX-SAUNA@users.noreply.github.com)). I have no idea where that even came from!

Looks OK now; there was a missed invitation for Canonical Contributor Agreement organization in the email! "_**You are now a member of CanonicalContributorAgreement!**_ "

**Comment by Feichtmeier** [comment]
Or you use git to change the email of this commit
you can do this for example in the terminal with
```bash
git commit --amend
```
then an editor opens and you can change the email
then you safe the file (if nano opened CTRL + O then CTRL + X)
then you need to overwrite this commit here with the commit in your local repo fork clone with
```bash
git push --force
``` 

if this is too annoying you can also make a new PR and make the commit there with the email you used in in launchpad CLA :)
Sorry this is a bit annoying =( I Know

**Comment by Feichtmeier** [comment]
Well well :) Now it worked :shrug: 

Eventually launchpad just needed 1 and a half day :older_man: Thanks for your patience!

**Comment by LINUX-SAUNA** [comment]
> Or you use git to change the email of this commit you can do this for example in the terminal with
> 
> ```shell
> git commit --amend
> ```
> 
> then an editor opens and you can change the email then you safe the file (if nano opened CTRL + O then CTRL + X) then you need to overwrite this commit here with the commit in your local repo fork clone with
> 
> ```shell
> git push --force
> ```
> 
> if this is too annoying you can also make a new PR and make the commit there with the email you used in in launchpad CLA :) Sorry this is a bit annoying =( I Know

Ok, no problem - check the message above - things seem to go to right direction :-)

**Pull request merged**
