### PR TITLE
BasePlate and FallBackIcon improvements

### PR DESCRIPTION
**Pull request by Feichtmeier**
- use a rounded square form to avoid clipping for hard edge square forms, i.e. to avoid this:
grafik

- adjust padding to make them look bigger when they are very small
- always make the fallback icon light to avoid bulls-eye effect, to be clear, to avoid this:
grafik

- adjust fallback icon borders

After (dark):
grafik
grafik
grafik
grafik

After (light):
grafik
grafik
grafik
grafik

### CODE REVIEW

**Review by madsrh — COMMENTED** [review]
I love the return of the squircle 😸

In the light theme there's IMO too many lines now. I think it looks much cleaner without the gray border.



I think we should remove the border and the drop shadow. This way you'll only notice the baseplate when using the dark theme.

Is there room enough for the icon size to return to 45? They seems very small.

**Comment by anasereijo** [comment]
> In the light theme there's IMO too many lines now. I think it looks much cleaner without the gray border.
> I think we should remove the border and the drop shadow. This way you'll only notice the baseplate when using the dark theme.

I agree, removing it makes the light theme look much cleaner 👍 

> Is there room enough for the icon size to return to 45? They seems very small.

Do you mean the actual icon inside the baseplate or the baseplate size? I actually quite like the size now (counting with the baseplate), I remember thinking it was way too big before? But happy to explore! We were thinking of making the app-name smaller too at some point, so hopefully it will all balance well together.

**Comment by madsrh** [comment]
> Do you mean the actual icon inside the baseplate or the baseplate size? 

Sorry, I meant for the appbanners here: (this is 40px)
borders

**Comment by anasereijo** [comment]
> The idea is very nice but then the alignment is wrong

That is a good point. It's more noticeable in the app-banners than on the app-page. 

What about a very light grey stroke?

windows example
Screenshot 2023-01-16 at 17 05 37

**Comment by Feichtmeier** [comment]
> 🤦‍♂️ Damn, ofc! and only adding the baseplate in the dark theme is a hacky solution? I'm asking for a friend 😅

The only reason I thought a baseplate was needed was because there are horrible, horrible icons out there, without any background but transparency #788 

We could also remove the baseplate again if we think we should rather contact the publishers with the shity icons (no irony)

**Comment by anasereijo** [comment]
This is actually a nice topic to bring up on my weekly design meeting (which is happening tomorrow). I will see what others think

**Comment by Feichtmeier** [comment]
Ok! I try the softer border as a solution to get this PR merged then. Because the approach currently in main has problems, as shown in the opening post. So we need to do something about it for now

**Comment by anasereijo** [comment]
> Ok! I try the softer border as a solution to get this PR merged then. Because the approach currently in main has problems, as shown in the opening post. So we need to do something about it for now

Makes sense! Go for it and we can the iterate a bit more

**Review by madsrh — APPROVED** [review]
Sorry, for getting sidetracked. Let's merge this now and circle back to it later.

**Comment by Feichtmeier** [comment]
https://github.com/ubuntu-flutter-community/software/issues/802

**Pull request merged**
