### PR TITLE
Appstream service to expose metadata and search for packages.

### LINKED ISSUE #128: Use appstream.dart for packagekit icons and screenshots
Unlike snapd, packagekit does not provide any icons or screenshots of the apps.
So to get those we need appstream.dart, which should be used in the package_service.dart here to fetch the metadata for X packages ad store them

IMO since snapd is so very fast with getting icons and screenshots I would not slow this app down by using appstream for snaps - Opinons ?  @oSoMoN @jpnurmi @Jupi007 

Depends on https://github.com/canonical/appstream.dart/issues/15

### PR DESCRIPTION
**Pull request by oSoMoN**
Fixes #128, #464, #509.

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thank you @oSoMoN  !
Will review this today evening or tomorrow

**Comment by oSoMoN** [comment]
Thanks @Feichtmeier ! No rush, it's a big one so take your time, I hope I haven't introduced regressions, but it's hard to be sure without a better test coverage.

**Comment by Feichtmeier** [comment]
Hey @oSoMoN - awesome work :muscle: 
Could not find anything in the code changes I could not agree with.
Images are also loading fine. And the search has become faster and I think #509 is also fixed with this

One thing has become worse though, the start up speed - it now lags after start (this is the compiled version and I added a .desktop shortcut):

https://user-images.githubusercontent.com/15329494/204093830-7be34c82-2893-435f-98d4-1a2adccce9b9.mp4

Maybe this is because you init the appstream service right in main?
Maybe it would be better to init the appstream service from within the init method of the store model?

**Comment by Feichtmeier** [comment]
@oSoMoN pulled again and here is the result. First I start the binary linux build from your branch then I close it and open the snap which contains main branch, the lag is still happening.


https://user-images.githubusercontent.com/15329494/204289544-08d16401-b070-4716-9e59-51cc7ef5edc8.mp4

I would suggest this patch to change where you init your service:

```git
diff --git a/lib/main.dart b/lib/main.dart
index 4a3ef44..8ab0591 100644
--- a/lib/main.dart
+++ b/lib/main.dart
@@ -58,8 +58,6 @@ Future<void> main(List<String> args) async {
     registerService<Connectivity>(Connectivity.new);
     registerService<SnapService>(SnapService.new);
 
-    getService<AppstreamService>().init();
-
     runApp(StoreApp.create());
   } else {
     final path = args.where((arg) => arg.endsWith('.deb')).first;
diff --git a/lib/store_app/store_app.dart b/lib/store_app/store_app.dart
index 71f58ac..e8fb941 100644
--- a/lib/store_app/store_app.dart
+++ b/lib/store_app/store_app.dart
@@ -20,6 +20,7 @@ import 'package:connectivity_plus/connectivity_plus.dart';
 import 'package:flutter/material.dart';
 import 'package:provider/provider.dart';
 import 'package:software/l10n/l10n.dart';
+import 'package:software/services/appstream_service.dart';
 import 'package:software/services/package_service.dart';
 import 'package:software/services/snap_service.dart';
 import 'package:software/store_app/common/animated_warning_icon.dart';
@@ -43,6 +44,7 @@ class StoreApp extends StatelessWidget {
           getService<Connectivity>(),
           getService<SnapService>(),
           getService<PackageService>(),
+          getService<AppstreamService>(),
         ),
         child: const StoreApp(),
       );
diff --git a/lib/store_app/store_model.dart b/lib/store_app/store_model.dart
index 3059846..e1f2514 100644
--- a/lib/store_app/store_model.dart
+++ b/lib/store_app/store_model.dart
@@ -20,6 +20,7 @@ import 'dart:async';
 import 'package:connectivity_plus/connectivity_plus.dart';
 import 'package:safe_change_notifier/safe_change_notifier.dart';
 import 'package:snapd/snapd.dart';
+import 'package:software/services/appstream_service.dart';
 import 'package:software/services/package_service.dart';
 import 'package:software/services/snap_service.dart';
 import 'package:software/updates_state.dart';
@@ -30,8 +31,11 @@ class StoreModel extends SafeChangeNotifier implements WindowListener {
     this._connectivity,
     this._snapService,
     this._packageService,
+    this._appstreamService,
   );
 
+  final AppstreamService _appstreamService;
+
   final SnapService _snapService;
   Map<Snap, SnapdChange> get snapChanges => _snapService.snapChanges;
   StreamSubscription<bool>? _snapChangesSub;
@@ -61,6 +65,7 @@ class StoreModel extends SafeChangeNotifier implements WindowListener {
     windowManager.setPreventClose(true);
     windowManager.addListener(this);
 
+    await _appstreamService.init();
     await _packageService.init();
 
     _snapChangesSub = _snapService.snapChangesInserted.listen((_) {
```

Result lags less, but it is still a bit slower than main

https://user-images.githubusercontent.com/15329494/204290847-01926f33-eb7f-4f17-a5b7-dd1e0ac399fd.mp4

**Comment by oSoMoN** [comment]
Hey @Feichtmeier I only rebased the branch on main because there were merge conflicts. I didn't actually address the issue you're raising here yet. I'm working on it though, I can definitely see the lag at startup and this needs to be addressed before we can merge this branch, obviously.

**Comment by Feichtmeier** [comment]
@oSoMoN alright! Sorry, I misinterpreted your force push as not-only-an-main-merge :P 

For further performance improvements I noticed locally when we change the package service init to 

```
  void init() {
    getInstalledPackages().then((_) => refreshUpdates());
  }
```

be not async, the performance even increases more but I can do this after your PR. As I would also like to re-visit the snap service and move the initialization of the explore model section map to the snap service, because it should not change throughout the lifetime of one app usage.

**Comment by oSoMoN** [comment]
I think https://github.com/canonical/appstream.dart/issues/13 would be key to a non-blocking Appstream service. I'm going to look into implementing it.

**Comment by Feichtmeier** [comment]
Okay merging from master is still only a button press here (I'll leave this to you ofc)
I'll stop merging stuff now to not create more conflicts

**Comment by oSoMoN** [comment]
> Okay merging from master is still only a button press here (I'll leave this to you ofc) I'll stop merging stuff now to not create more conflicts

No, that's alright, feel free to continue merging things, I'll rebase as needed. I don't want this work to be blocking other contributions.

**Comment by oSoMoN** [comment]
https://github.com/canonical/appstream.dart/issues/13 has been implemented and released (with appstream.dart 0.2.7), and I rebased this PR on the latest main (and made sure the new appstream service is initialized in the store model, like other services). @Feichtmeier I believe this addresses the performance issue you were observing, can you please confirm?

**Comment by Feichtmeier** [comment]
https://user-images.githubusercontent.com/15329494/204810430-bdd4f930-c022-46da-b5e7-f9e1b1f958bf.mp4

Waiting for the store model initi to finish takes now longer. But once it is inited I can not see any lag 
So I would say let's get this in and eventually think about how we can decrease the start-up time?

**Review by Feichtmeier — APPROVED** [review]

**Comment by oSoMoN** [comment]
Yes, that sounds good to me. We should probably try not to `await` for all the services to be initialized, but this needs careful testing to ensure the app remains fully functional while still initializing. Definitely something to investigate in a follow-up issue/PR.

**Pull request merged**
