### PR TITLE
Create it translation

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by albanobattistella** [comment]
> Hey! albanobattistella has not signed the Canonical CLA which is required to get this contribution merged on this project.
> 
> Please head over to https://ubuntu.com/legal/contributors to read more about it.

Done!

**Comment by Feichtmeier** [comment]
Grazie mille!

The test sometimes needs one or two full days two see that your email addresses match. I'll rerun it again tomorrow 😅💤🧐

**Comment by Feichtmeier** [comment]
@albanobattistella are you sure that the email addresses match?

**Comment by albanobattistella** [comment]
> @albanobattistella are you sure that the email addresses match?

Hi, I received an email today...and it is correct.

**Comment by jpnurmi** [comment]
@albanobattistella The CLA bot is not able to recognize you as [albano-battistella](https://launchpad.net/~albano-battistella) on Launchpad because the commits were made as `34811668+albanobattistella@users.noreply.github.com`:

```
Checking the following users on GitHub:
- albanobattistella ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- 34811668+albanobattistella@users.noreply.github.com ✕ (has no Launchpad account)
```

Is your e-mail marked private on GitHub (settings -> emails)?
image

**Comment by Feichtmeier** [comment]
@albanobattistella we got something better for translation now
Please check out
https://github.com/ubuntu-flutter-community/software/blob/main/CONTRIBUTING.md#translations

**Pull request closed without merging**
