### PR TITLE
AppPage and package updates in wide windows: limit adaptive padding

### LINKED ISSUE #861: AppPage in wide windows: remove adaptive padding
https://user-images.githubusercontent.com/3986894/214158165-404082f2-edac-441b-a9b6-8572806bc83b.mp4

### PR DESCRIPTION
**Pull request by Feichtmeier**
@madsrh but on a sidenote, I think we've spoken about this many many times. You need to apply the scaling if you are on a 4k screen :) You and no other designer will be able to design a layout that works on a 1:1 scaling on a 4k screen. I wonder why you always check those 4k 1:1 resolutions? :) 

grafik

Fixes #861

### CODE REVIEW

**Comment by Feichtmeier** [comment]
We could check each indiviual section in wide mode (NOT ON A 4K SCREEN WITH 1:1 scaling) and see if we need to make edge cases like in the gallery
grafik

**Review by madsrh — COMMENTED** [review]
I prefer the current master. It works perfect until +1800px

Would it be possible (with master) after a certain width to "freeze" the width of the green part and only add padding or ?

image

**Comment by Feichtmeier** [comment]
yes

**Comment by Feichtmeier** [comment]
but this wont stop you from using the appon a 4k scrren with 100% scaling ;)

**Comment by Feichtmeier** [comment]
Instead of adding a limit to scaling we could add a limit to the window size. Which would ofc not change 200% scaling

**Comment by madsrh** [comment]
> Instead of adding a limit to scaling we could add a limit to the window size. Which would ofc not change 200% scaling

You will know what the best solution is here 🤷‍♂️ What would happen if I maximized the window then? I think the padding solution is "simpler".

>  ...on a sidenote, I think we've spoken about this many many times...

We have indeed and sorry for bringing it up again, but even if it's an edge cast, I think we should plan for it. And no, I don't actually use my desktop in this 100% mode 😄 

It looks odd, but this Microsoft solution is better than overflow.
image

**Comment by Feichtmeier** [comment]
We can fix the overflow. But we can not design for those edge cases. It's impossible and will affect the actual target resolutions and scales in a bad way. I'm not saying this is not an issue in just a bit .... "surprised" that we are here again... Looking at a 4k+ screen with 100% scaling. Windows is much better at 4k scaling most importantly because it immediately suggests a 150-200% scaling the moment it detects an enormous amount of pixels. Ubuntu doesn't do this and yeah.... Here we are. But this is not our problem at least not in this repo, seriously 😒

**Comment by madsrh** [comment]
> We can fix the overflow. 

If it's a small fix that would ofc be good 👍 

Sorry for bringing it up again. Other than this edge case, I'm **very** happy with the current layout(s), so let's just close this 😸

**Comment by Feichtmeier** [comment]
no it's an issue, we can fix it

**Comment by Feichtmeier** [comment]
@madsrh 

grafik

please test on your times square screen :)

**Review by madsrh — APPROVED** [review]
YES!!! This work - Thank you 🙏

**Pull request merged**
