### PR TITLE
AppInfos: improve reaction to available space

### LINKED ISSUE #763: AppInfos: improve reaction to available space
The app info section currently behaves badly when the space changes they are drawn in which can result in strange situations

grafik
grafik

I propose to use a gridview instead which also makes it possible to "skip" elements:

https://user-images.githubusercontent.com/15329494/212267148-f530b774-761e-43e7-912a-4b848bc90efc.mp4

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #763

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@d-loose any idea how this change, which does not touch anything used in the integration test, makes the test fail?

```
WARNING: A call to pumpUntil() with finder "zero widgets with widget matching predicate (Closure: (Widget) => bool) which is an ancestor of text "Remove"" did not complete within the specified timeout 0:00:40.000000.
#0      WidgetTesterX.pumpUntil.<anonymous closure> (file:///home/runner/work/software/software/test/test_utils.dart:32:135)
#1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#3      _rootRun (dart:async/zone.dart:1383:47)
#4      _CustomZone.run (dart:async/zone.dart:1293:19)
#5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:864:34)
#6      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#7      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#8      _rootRun (dart:async/zone.dart:1383:47)
#9      _CustomZone.run (dart:async/zone.dart:1293:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1241:23)
#12     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:208:15)
#13     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:116:48)
#14     _rootRun (dart:async/zone.dart:1391:13)
#15     _CustomZone.run (dart:async/zone.dart:1293:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1225:23)
#17     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching node in the widget tree
  Actual: _AncestorFinder:<zero widgets with widget matching predicate (Closure: (Widget) => bool)
which is an ancestor of text "Remove">
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect (package:test_api/src/expect/expect.dart:129:3)
#2      expect (package:test_api/src/expect/expect.dart:46:3)
#3      expectSync (package:flutter_test/src/widget_tester.dart:477:16)
#4      testInstallPackage (file:///home/runner/work/software/software/integration_test/software_test.dart:102:3)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Install and remove local deb
════════════════════════════════════════════════════════════════════════════════════════════════════

01:46 +0 -1: Package Installer App Install and remove local deb [E]                                                                                                                                    
  Test failed. See exception logs above.
  The test description was: Install and remove local deb
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 1754 pos 12: '_pendingFrame == null': is not true.
  dart:core                                                                   _AssertionError._throwNew
  package:flutter_test/src/binding.dart 1754:12                               LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                      _GuaranteeSink.add
  /tmp/flutter_tools.EUIGWH/flutter_test_listener.CUULVA/listener.dart 53:22  main.<fn>
  

To run this test again: /opt/hostedtoolcache/flutter/stable-3.3.10-x64/bin/cache/dart-sdk/bin/dart test /home/runner/work/software/software/integration_test/software_test.dart -p vm --plain-name 'Package Installer App Install and remove local deb'

01:46 +0 -1: Package Installer App Install and remove snap                                                                                                                                             
01:46 +0 -2: Package Installer App Install and remove snap [E]                                                                                                                                         
  'package:flutter_test/src/binding.dart': Failed assertion: line 1729 pos 12: '!inTest': is not true.
  dart:core                                                                   _AssertionError._throwNew
  package:flutter_test/src/binding.dart 1729:12                               LiveTestWidgetsFlutterBinding.runTest
  package:integration_test/integration_test.dart 238:17                       IntegrationTestWidgetsFlutterBinding.runTest
  package:flutter_test/src/widget_tester.dart 164:24                          testWidgets.<fn>
  ===== asynchronous gap ===========================
  package:stream_channel                                                      _GuaranteeSink.add
  /tmp/flutter_tools.EUIGWH/flutter_test_listener.CUULVA/listener.dart 53:22  main.<fn>
  
  'package:flutter_test/src/binding.dart': Failed assertion: line 1754 pos 12: '_pendingFrame == null': is not true.
  dart:core                                                                   _AssertionError._throwNew
  package:flutter_test/src/binding.dart 1754:12                               LiveTestWidgetsFlutterBinding.postTest
  ===== asynchronous gap ===========================
  package:stream_channel                                                      _GuaranteeSink.add
  /tmp/flutter_tools.EUIGWH/flutter_test_listener.CUULVA/listener.dart 53:22  main.<fn>
  

To run this test again: /opt/hostedtoolcache/flutter/stable-3.3.10-x64/bin/cache/dart-sdk/bin/dart test /home/runner/work/software/software/integration_test/software_test.dart -p vm --plain-name 'Package Installer App Install and remove snap'

01:46 +0 -2: (tearDownAll)                                                                                                                                                                             
01:46 +0 -2: Some tests failed.                                                                                                                                                                        
Error: Process completed with exit code 1.
```

**Comment by d-loose** [comment]
The test fails due to a timeout while waiting for the installation of the local deb package to finish. It works fine locally - maybe it's related to this morning's issues with azure.archive.ubuntu.com?

**Comment by Feichtmeier** [comment]
Weird output for this fail :)

I've massaged the ci, like Jp would say, let's see if it passed now

**Comment by d-loose** [comment]
Works now :)

**Review by madsrh — APPROVED** [review]

**Comment by Feichtmeier** [comment]
Just fixed that the scrollbars in this grid are not shown to have a full "hide" after your review

**Pull request merged**
