### PR TITLE
SnapPage: add a share button

### LINKED ISSUE #1047: SnapPage: add a share button

### PR DESCRIPTION
**Pull request by Feichtmeier**
image

image

image

Fixes #1047

### CODE REVIEW

**Review by madsrh — APPROVED** [review]
Yes, share that snap! 😄 Some feedback you can consider:

Could you add a "share" tooltip? PR https://github.com/ubuntu-flutter-community/software/pull/1057

IMO the snackbar design is really very phonesentric and in a desktop app, the full width inverted surface feels massive.


I wonder if we could do something like this?

**Comment by madsrh** [comment]
@Feichtmeier sorry for tagging you, I wasn't sure if you've missed this comment since the PR is closed, or if you just disagree 🐱 👆

**Comment by Feichtmeier** [comment]
I like the color but I agree that we dont always need the full width

Actually M3 snackbars should look like this
grafik

I wonder if this is an issue in yaru.dart

**Comment by madsrh** [comment]
> I like the color but I agree that we dont always need the full width

+1 we need that color to grab the users attention

**Pull request merged**
