### PR TITLE
SnapModel: toggle connections correctly

### LINKED ISSUE #131: SnapModel: toggle connections correctly
Here the connections that are established for the corresponding snap are loaded

https://github.com/ubuntu-flutter-community/software/blob/8af4ad3dd648c42e240b2d50382f2df3eaea2f24/lib/store_app/common/snap_model.dart#L330-L345

I tried to toggle a connection on and off and get the connections for this snap again but load the ones that are established and not established but the not established / un-toggled connections were not discoverable (for me).

We've spoke about this on Telegram before @robert-ancell - could you look at this again and give a hint how to solve this? 

Connect / disconnect works fine

https://github.com/ubuntu-flutter-community/software/blob/8af4ad3dd648c42e240b2d50382f2df3eaea2f24/lib/store_app/common/snap_model.dart#L304-L328

But currently the switches do nothing because toggling a connection off would remove them from the list and make them dissappear "forever" in the view.

### PR DESCRIPTION
**Pull request by Feichtmeier**
Fixes #131

### CODE REVIEW

**Comment by Feichtmeier** [comment]
@robert-ancell @jpnurmi 

Sorry to bother you again with this topic, but this connecting and disconnecting is not working.
Disconnecting works but the response is delayed, connect does not work at all. 
Would be awesome if you could take a look if I toggle this correctly, I have the impression that there is something wrong either in how I do it or in snapd.dart 
:cry:

**Comment by jpnurmi** [comment]
@Feichtmeier Is it possible to create a minimal Dart snippet to reproduce the problem? (something similar to snapd.dart/examples/*.dart)

**Comment by Feichtmeier** [comment]
Hi @jpnurmi :bow: 

This is the most minimal code I could extract from those  classes from the software app:

```dart
import 'package:flutter/material.dart';
import 'package:snapd/snapd.dart';

const snapName = 'slack';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: SlackConnections(),
    );
  }
}

class SlackConnections extends StatelessWidget {
  const SlackConnections({
    super.key,
  });
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FutureBuilder(
            future: loadPlugs(),
            builder: (context, snapshot) {
              if (!snapshot.hasData) return const SizedBox();

              return ListView.builder(
                padding: const EdgeInsets.all(20.0),
                itemCount: snapshot.data!.length,
                itemBuilder: (context, index) {
                  final plugEntry = snapshot.data!.entries.elementAt(index);
                  return Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(plugEntry.key.interface ?? ''),
                      Switch(
                        value: plugEntry.value,
                        onChanged: (value) async {
                          // HELP
                        },
                      )
                    ],
                  );
                },
              );
            }),
      ),
    );
  }

  Future<Map<SnapPlug, bool>> loadPlugs() async {
    final Map<SnapPlug, bool> plugs = {};
    final client = SnapdClient();

    await client.loadAuthorization();

    try {
      final response = await client.getConnections(
        snap: snapName,
        filter: SnapdConnectionFilter.all,
      );
      for (final plug in response.plugs) {
        if (plug.snap != 'snapd' &&
            plug.interface != null &&
            !plug.interface!.contains('content')) {
          if (plug.connections.isNotEmpty) {
            plugs.putIfAbsent(plug, () => true);
          } else {
            plugs.putIfAbsent(plug, () => false);
          }
        }
      }
    } on SnapdException {
      return {};
    }

    client.close();

    return plugs;
  }

  Future<Map<String, SnapConnection>> loadConnections(
    Snap snap,
  ) async {
    final client = SnapdClient();

    Map<String, SnapConnection> cons = {};
    await client.loadAuthorization();
    final response = await client.getConnections(
      filter: SnapdConnectionFilter.all,
      snap: snap.name,
    );

    for (final connection in [...response.undesired, ...response.established]) {
      final interface = connection.interface;
      if (interface != 'content') {
        cons.putIfAbsent(
          interface,
          () => connection,
        );
      }
    }

    client.close();

    return cons;
  }

  Future<void> connect({
    required SnapConnection con,
  }) async {
    final client = SnapdClient();

    await client.loadAuthorization();
    if ((await client.getChanges(
      filter: SnapdChangeFilter.inProgress,
      name: con.plug.snap,
    ))
        .isNotEmpty) return null;
    final changeId = await client.connect(
      con.plug.snap,
      con.plug.plug,
      con.slot.snap,
      con.slot.slot,
    );
    client.close();
  }

  Future<void> disconnect({
    required SnapConnection con,
  }) async {
    final client = SnapdClient();

    await client.loadAuthorization();
    if ((await client.getChanges(
      filter: SnapdChangeFilter.inProgress,
      name: con.plug.snap,
    ))
        .isNotEmpty) return null;
    final changeId = await client.disconnect(
      con.plug.snap,
      con.plug.plug,
      con.slot.snap,
      con.slot.slot,
    );

    client.close();
  }
}
```

**Comment by robert-ancell** [comment]
I've put some [examples](https://github.com/canonical/snapd.dart/pull/75) for connect/disconnect. In short, these are much like the install operation - they are asynchronous and can take a long time to complete depending on what snapd has to do. This is probably why they look delayed - the connect is only started after calling this method.

**Comment by Feichtmeier** [comment]
Thank you @robert-ancell 

I think I was really confused by all those words
snapplug plugsnap slotsnap interface xD 

It works now:

[snapplugplugsnapslotplug.webm](https://user-images.githubusercontent.com/15329494/192985624-cfdc8b7e-81d1-4689-8c83-b4da2e39dc4e.webm)

Just one thing: 

```dart
 String? slotSnap;
  String? slot;
  if (args.length > 1) {
    var tokens = args[1].split(':');
    if (tokens.length > 2) {
      usage();
      return;
    }
    slotSnap = tokens[0];
    slot = tokens.length == 2 ? tokens[1] : null;
  }
  ```

Why are you splitting the string once more? 

In my scenario I have a bunch of Snap instances
And I got the list of SnapPlug instances where I extract the interface String from

So I basically only have 

I want to connect this Snap instance's name String to this interface String

**Pull request merged**
