### PR TITLE
Make the textfield and the appbar for the MyApps page more consistent. 

### LINKED ISSUE #514: Align text and icon between the text field and the headerbar.
I think this was already mentioned in #432, but I'm still seeing the issue persist in the latest master release. I already wrote a PR with a fix for it, #513 with more visual information.

### PR DESCRIPTION
**Pull request by whiskeyPeak**
Lines up the icon and text between the textfield and appbar.
I also modified the the icon because the other back button looked a little blurry. Personally think this looks a little cleaner.

<details>

<summary>Before:</summary>

Before:
Screenshot from 2022-11-14 03-42-42

Screenshot from 2022-11-14 03-42-55

</details>

<details>

<summary>After:</summary>

After:
Screenshot from 2022-11-14 03-37-36

Screenshot from 2022-11-14 03-37-50

</details>

Fixes #514

### CODE REVIEW

**Comment by whiskeyPeak** [comment]
Here's a video showing the changes in a clearer way

https://user-images.githubusercontent.com/73116038/201575220-462214b0-5b7c-473a-874f-a280b61672fa.mp4

**Comment by Feichtmeier** [comment]
hi @whiskeyPeak 
thanks for the issue and the pull request

good idea with the padding!

the icon however should not be changed, it is the same icon and meaning we also use in the gnome theme
grafik

if it is blurry we need to try to fix it on the yaru_icons repository

**Comment by Feichtmeier** [comment]
@whiskeyPeak and could you also apply this padding change in the search field of the myapps page? they are currently not unified yet
grafik

**Comment by whiskeyPeak** [comment]
Thanks for the feedback! I've addressed all of it so this should be ready for merging.

**Comment by Feichtmeier** [comment]
The cla check sometimes needs 1 - 2 days to see your signment :) I will re-run it from time to time 👍 THanks for taking the time

**Comment by whiskeyPeak** [comment]
> The cla check sometimes needs 1 - 2 days to see your signment :) I will re-run it from time to time +1 THanks for taking the time

Ah I see, thank you for letting me know :)

**Comment by whiskeyPeak** [comment]
Huh this is weird. The CLA-check was approved for the other PR.

**Comment by Feichtmeier** [comment]
Checking the following users on GitHub:
- whiskeyPeak ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- 73116038+whiskeyPeak@users.noreply.github.com ✕ (has no Launchpad account)

I think because you updated the branch from github, the email do not match 😆 
Since one of your PRs has been passed the test with your email I would merge this PR.
Any veto @oSoMoN ?

**Comment by oSoMoN** [comment]
For the CLA check to work, I think @whiskeyPeak would have to provide an e-mail address on [their launchpad account](https://launchpad.net/~dalcoy96) that matches the one used in the commits, or would need to be added to https://github.com/CanonicalContributorAgreement. Either way, I don't have anything against merging this.

**Comment by whiskeyPeak** [comment]
> I think because you updated the branch from github, the email do not match laughing Since one of your PRs has been passed the test with your email I would merge this PR. Any veto @oSoMoN ?

Ahhh yes, that seems to have been the issue! All fixed now :)

**Pull request merged**
